'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.269
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GW2_Builder.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property Aimed_Shot_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aimed_Shot_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Arcing_Arrow_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arcing_Arrow_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Arcing_Slice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arcing_Slice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Backbreaker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Backbreaker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Backstab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Backstab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Banish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Banish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Barrage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Barrage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Binding_Blade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Binding_Blade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Black_Powder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Black_Powder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Bladetrail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bladetrail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Bleeding_Shot_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bleeding_Shot_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Blowtorch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blowtorch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Blunderbuss() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blunderbuss", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Body_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Body_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Bonfire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bonfire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Brutal_Shot_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brutal_Shot_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Brutal_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brutal_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Call_of_the_Wild() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Call_of_the_Wild", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Call_to_Arms_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Call_to_Arms_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Chains_of_Light_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chains_of_Light_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Charge_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Charge_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Choking_Gas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Choking_Gas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Chop_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chop_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Cleansing_Flame_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cleansing_Flame_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Cloak_and_Dagger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cloak_and_Dagger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Cluster_Bomb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cluster_Bomb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Combustive_Shot_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Combustive_Shot_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Concussion_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Concussion_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Counter_Blow_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Counter_Blow_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Counterattack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Counterattack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Crippling_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crippling_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Crippling_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crippling_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Crippling_Talon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crippling_Talon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Crippling_Throw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crippling_Throw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Cross_Fire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cross_Fire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Crushing_Blow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Crushing_Blow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Cyclone_Axe_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cyclone_Axe_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property damage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("damage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Dancing_Dagger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dancing_Dagger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Death_Blossom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Death_Blossom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Detonate_Cluster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Detonate_Cluster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Disabling_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Disabling_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Double_Chop_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Double_Chop_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Double_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Double_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Dual_Shot_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dual_Shot_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Dual_Strike_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dual_Strike_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Earthshaker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Earthshaker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property elementalist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elementalist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property elementalist_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("elementalist_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property engineer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property engineer_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Eviscerate_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eviscerate_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Explosive_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosive_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Faithful_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Faithful_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Fan_of_Fire_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fan_of_Fire_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Fierce_Blow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fierce_Blow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Final_Thrust_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Final_Thrust_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Flanking_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flanking_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Flash_of_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flash_of_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Flashing_Blade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flashing_Blade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Flurry_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flurry_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Gash_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gash_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Glue_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Glue_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Greatsword_Slice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Greatsword_Slice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Greatsword_Swing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Greatsword_Swing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property guardian() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guardian", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property guardian_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guardian_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Hammer_Bash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hammer_Bash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Hammer_Bash1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hammer_Bash1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Hammer_Shock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hammer_Shock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Hammer_Smash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hammer_Smash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Hammer_Swing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hammer_Swing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Hammer_Swing1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hammer_Swing1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Hamstring_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hamstring_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Head_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Head_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Heartseeker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Heartseeker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Hilt_Bash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hilt_Bash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Hip_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hip_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Hornet_Sting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hornet_Sting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Hundred_Blades() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hundred_Blades", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Hunter_s_Call() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hunter_s_Call", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Hunter_s_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hunter_s_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Impale_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Impale_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Infiltrator_s_Arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Infiltrator_s_Arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Infiltrator_s_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Infiltrator_s_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Jump_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jump_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Kick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Kill_Shot_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kill_Shot_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Leap_of_Faith() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Leap_of_Faith", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Line_of_Warding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Line_of_Warding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Long_Range_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Long_Range_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Lotus_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lotus_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Mace_Bash_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mace_Bash_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Mace_Smash_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mace_Smash_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Magnetic_Field() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magnetic_Field", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Martyr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Martyr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Maul() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maul", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property mesmer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mesmer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property mesmer_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mesmer_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Mighty_Blow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mighty_Blow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Monarch_s_Leap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Monarch_s_Leap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property necromancer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("necromancer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property necromancer_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("necromancer_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Net_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Net_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property null() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("null", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Orb_of_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Orb_of_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Orb_of_Wrath_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Orb_of_Wrath_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Overcharged_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Overcharged_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Path_of_Scars() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Path_of_Scars", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Pin_Down_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pin_Down_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Pistol_Whip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pistol_Whip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Point_Blank_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Point_Blank_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Poison_Dart_Volley() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Poison_Dart_Volley", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Poison_Volley() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Poison_Volley", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Pommel_Bash_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pommel_Bash_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Pounce() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pounce", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Power_Stab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Power_Stab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Protector_s_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Protector_s_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Pulverize_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pulverize_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Pure_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pure_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Quick_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Quick_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property range() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("range", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ranger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ranger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ranger_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ranger_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Rapid_Fire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rapid_Fire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Ray_of_Judgment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ray_of_Judgment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Repeater() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Repeater", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Ricochet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ricochet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Rifle_Butt_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rifle_Butt_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Ring_of_Warding() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ring_of_Warding", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Riposte_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Riposte_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Rush() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rush", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Savage_Leap_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Savage_Leap_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Serpent_s_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Serpent_s_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Sever_Artery_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sever_Artery_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Shadow_Return() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shadow_Return", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Shadow_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shadow_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Shadow_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shadow_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Shield_Bash_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shield_Bash_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Shield_of_Absorption_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shield_of_Absorption_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Shield_of_Judgment_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shield_of_Judgment_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Shield_of_Wrath() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shield_of_Wrath", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Shield_Stance_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shield_Stance_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Skull_Crack_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skull_Crack_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Slash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Slash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Slash1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Slash1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Slice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Slice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Slice1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Slice1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Smite_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Smite_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Smoldering_Arrow_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Smoldering_Arrow_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Sneak_Attack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sneak_Attack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Splitblade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splitblade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Stab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Staggering_Blow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Staggering_Blow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Stalker_s_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stalker_s_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Static_Shield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Static_Shield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Static_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Static_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Suprise_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Suprise_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Switch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Switch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Swoop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Swoop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Sword_Arc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sword_Arc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Sword_of_Wrath() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sword_of_Wrath", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Sword_Wave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sword_Wave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Symbol_of_Faith() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Symbol_of_Faith", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Symbol_of_Protection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Symbol_of_Protection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Symbol_of_Swiftness() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Symbol_of_Swiftness", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Symbol_of_Wrath() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Symbol_of_Wrath", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Tactical_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tactical_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property thief() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thief", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property thief_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thief_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Throw_Axe_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Throw_Axe_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Throw_Torch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Throw_Torch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Tremor_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tremor_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Trick_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trick_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Triple_Chop_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Triple_Chop_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property True_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("True_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Twisting_Fangs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Twisting_Fangs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Unknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Unknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Vengeful_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vengeful_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Vital_Shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vital_Shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Volley_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Volley_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property warrior() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warrior", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property warrior_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warrior_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Wave_of_Wrath() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wave_of_Wrath", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Whirling_Axe_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Whirling_Axe_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Whirling_Defense() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Whirling_Defense", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Whirling_Wrath() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Whirling_Wrath", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Whirlwind_Attack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Whirlwind_Attack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Wild_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wild_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Winter_s_Bite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Winter_s_Bite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Wrathful_Strike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wrathful_Strike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Zealot_s_Defense() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zealot_s_Defense", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Zealot_s_Embrace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zealot_s_Embrace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Zealot_s_Fire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zealot_s_Fire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Zealot_s_Flame_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zealot_s_Flame_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
